package:
  name: r-conda-demo2
  version: "1.0"

build:
  number: 0

source:
  git_rev: HEAD
  git_url: https://github.com/marpobuda/r_conda_demo.git

requirements:
  build:
    - python
    - r-base
    - r-arcgisbinding
    - r-dbscan
  run:
    - r-base
    - r-arcgisbinding
    - r-dbscan

about:
  home: https://github.com/marpobuda/r_conda_demo
